apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-service.fullname" . }}-secret
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.database.password | quote }}

