apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "order-service.fullname" . }}-secret
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
spec:
  encryptedData:
    DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | quote }}
  template:
    type: Opaque
    metadata:
      labels:
        {{- include "order-service.labels" . | nindent 8 }}
