apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team2-kafka
  namespace: argocd
spec:
  project: team2
  
  source:
    repoURL: https://github.com/CSU-ITMO-2025-2/team2-helm-agro
    targetRevision: security
    path: deploy/helm/kafka
  
  destination:
    server: https://kubernetes.default.svc
    namespace: team2
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
