apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-2-postgres
  namespace: argocd
spec:
  project: team-2
  
  source:
    repoURL: https://github.com/CSU-ITMO-2025-2/team-2-helm-agro
    targetRevision: security
    path: deploy/helm/postgres
  
  destination:
    server: https://kubernetes.default.svc
    namespace: team-2
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
