apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secret
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
