apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "api-gateway.fullname" . }}-secret
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  encryptedData:
    JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  template:
    type: Opaque
    metadata:
      labels:
        {{- include "api-gateway.labels" . | nindent 8 }}
