apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-zookeeper
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    component: zookeeper
spec:
  type: ClusterIP
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: client
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
    component: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-zookeeper-headless
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    component: zookeeper
spec:
  clusterIP: None
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: client
    - port: 2888
      targetPort: 2888
      protocol: TCP
      name: follower
    - port: 3888
      targetPort: 3888
      protocol: TCP
      name: election
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
    component: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-kafka
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    component: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: broker
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
    component: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-kafka-headless
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    component: kafka
spec:
  clusterIP: None
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: broker
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
    component: kafka

