apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "postgres.fullname" . }}-secret
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  encryptedData:
    POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  template:
    type: Opaque
    metadata:
      labels:
        {{- include "postgres.labels" . | nindent 8 }}
    data:
      POSTGRES_USER: {{ .Values.database.user | b64enc }}
      POSTGRES_DB: {{ .Values.database.name | b64enc }}
