# Global values for all services (optional)
global: {}

# Sealed Secrets configuration
sealed-secrets:
  enabled: true
  installCRDs: true
  namespace: kube-system
  rbac:
    create: true
    clusterRole: true

# Override values for individual services if needed
postgres:
  enabled: true

kafka:
  enabled: true

order-service:
  enabled: true

api-gateway:
  enabled: true

notification-service:
  enabled: true

analytics-service:
  enabled: true
