apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team2-app
  namespace: argocd
spec:
  project: team2
  
  source:
    repoURL: https://github.com/CSU-ITMO-2025-2/team-2-helm-agro
    targetRevision: security-argocd
    path: deploy/helm
    helm:
      releaseName: team2
  
  destination:
    server: https://kubernetes.default.svc
    namespace: team2-ns
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true